trigger:
  branches:
    include:
      - azuredevops  # Change this to your actual default branch if different

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Create screenshots/ folder if not exists
  - script: |
      mkdir -p screenshots
    displayName: 'Create screenshots folder'

  # Step 2: List the contents of src/test/resources/TestRunners folder
  - script: |
      echo "Listing contents of src/test/resources/TestRunners/ folder"
      ls -l src/test/resources/TestRunners/
    displayName: 'List contents of TestRunners folder'

  # Step 3: Run Maven Tests
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-Dsurefire.suiteXmlFiles=src/test/resources/TestRunners/testng_regression.xml'
    displayName: 'Run Maven TestNG Suite'

  # Step 4: Publish Allure Raw Results
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-results'
      artifact: 'allure-results'
      publishLocation: 'pipeline'
    displayName: 'Publish Allure Raw Results'

  # Step 5: Install Allure CLI
  - script: |
      sudo apt-get update
      sudo apt-get install -y allure
    displayName: 'Install Allure CLI'

  # Step 6: Generate Allure Final Report
  - script: |
      allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure Report'

  # Step 7: Publish Allure Final Report
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-report'
      artifact: 'allure-report'
      publishLocation: 'pipeline'
    displayName: 'Publish Allure Report'

  # Step 8: Publish Extent Reports Folder
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'reports'
      artifact: 'extent-reports'
      publishLocation: 'pipeline'
    displayName: 'Publish Extent Reports'

  # Step 9: Publish Screenshots Folder
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'screenshots'
      artifact: 'screenshots'
      publishLocation: 'pipeline'
    displayName: 'Publish Screenshots'
